"""LaTeX 表格导出 — 将复现结果生成可嵌入论文的表格"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from reprochecker.storage.db import Database

db = Database()


def generate_latex(
    check_id: int,
    output_dir: Path | None = None,
) -> Path:
    """生成 LaTeX 表格文件

    Args:
        check_id: 检验记录 ID
        output_dir: 输出目录，默认使用配置的报告目录

    Returns:
        生成的 .tex 文件路径
    """
    record = db.get_check(check_id)
    if not record:
        raise ValueError(f"检验记录 #{check_id} 不存在")

    comparisons = db.get_comparisons(check_id)

    output_dir = output_dir or Path(".")
    output_dir.mkdir(parents=True, exist_ok=True)
    path = output_dir / f"repro_{check_id}.tex"

    sections: list[str] = []
    sections.append(_header(record))
    if comparisons:
        sections.append(_comparison_table(comparisons))
    sections.append(_score_table(record))
    sections.append(_footer())

    path.write_text("\n\n".join(sections) + "\n", encoding="utf-8")
    db.update_check(check_id, report_path=str(path))
    return path


def _esc(text: str) -> str:
    """转义 LaTeX 特殊字符"""
    # 注意：反斜杠必须最先处理，否则会重复转义
    text = text.replace("\\", r"\textbackslash{}")
    replacements = {
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
        "_": r"\_",
        "&": r"\&",
        "%": r"\%",
        "#": r"\#",
        "$": r"\$",
        "{": r"\{",
        "}": r"\}",
        ">": r"\textgreater{}",
    }
    for old, new in replacements.items():
        text = text.replace(old, new)
    return text


def _header(record: dict[str, Any]) -> str:
    repo = _esc(record.get("repo_name", "") or record.get("repo_url", ""))
    grade = record.get("grade", "-") or "-"
    score = record.get("overall_score", 0) or 0

    return (
        f"% ReproChecker 复现报告 — {repo}\n"
        f"% 等级: {grade} ({score:.0f}/100)\n"
        f"% 自动生成，可直接嵌入 LaTeX 文档\n"
    )


def _comparison_table(comparisons: list[dict[str, Any]]) -> str:
    lines = [
        r"\begin{table}[htbp]",
        r"  \centering",
        r"  \caption{复现结果与论文值对比}",
        r"  \label{tab:repro-comparison}",
        r"  \begin{tabular}{lrrrr}",
        r"    \toprule",
        r"    指标 & 论文值 & 实际值 & 相对误差 & 达标 \\",
        r"    \midrule",
    ]

    for c in comparisons:
        name = _esc(str(c.get("metric_name", "")))
        paper = c.get("paper_value")
        actual = c.get("actual_value")
        error = c.get("relative_error")
        ok = c.get("within_tolerance")

        paper_s = f"{paper:.4f}" if paper is not None else "-"
        actual_s = f"{actual:.4f}" if actual is not None else "-"
        error_s = f"{error:.2f}\\%" if error is not None else "-"
        ok_s = r"\checkmark" if ok else r"$\times$"

        lines.append(f"    {name} & {paper_s} & {actual_s} & {error_s} & {ok_s} \\\\")

    lines.extend([
        r"    \bottomrule",
        r"  \end{tabular}",
        r"\end{table}",
    ])
    return "\n".join(lines)


def _score_table(record: dict[str, Any]) -> str:
    metric = record.get("metric_score", 0) or 0
    env = record.get("env_score", 0) or 0
    code = record.get("code_score", 0) or 0
    overall = record.get("overall_score", 0) or 0
    grade = record.get("grade", "-") or "-"

    lines = [
        r"\begin{table}[htbp]",
        r"  \centering",
        r"  \caption{复现评分明细}",
        r"  \label{tab:repro-scores}",
        r"  \begin{tabular}{lrl}",
        r"    \toprule",
        r"    维度 & 分数 & 权重 \\",
        r"    \midrule",
        f"    指标复现 & {metric:.0f} & 50\\% \\\\",
        f"    环境复现 & {env:.0f} & 20\\% \\\\",
        f"    代码质量 & {code:.0f} & 30\\% \\\\",
        r"    \midrule",
        f"    总分 & {overall:.0f} & — \\\\",
        f"    等级 & {grade} & — \\\\",
        r"    \bottomrule",
        r"  \end{tabular}",
        r"\end{table}",
    ]
    return "\n".join(lines)


def _footer() -> str:
    return "% Generated by ReproChecker v0.1.0"
